<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Computadora extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Computadora_model');
        $this->load->helper(array('form', 'url'));
        $this->load->library('form_validation');
        $this->load->helper('security');
        $this->load->library('tank_auth');
        $this->lang->load('tank_auth');
        $this->load->library('mydompdf');
    } 

    /*
     * Listing of computadoras
     */
    function index()
    {
        $data['computadoras'] = $this->Computadora_model->get_all_computadoras();

        $data['_view'] = 'computadora/index';
        $this->load->view('_template_principal',$data);
    }

    /*
     * Adding a new computadora
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'tipoc' => $this->input->post('tipoc'),
				'ram' => $this->input->post('ram'),
				'procesador' => $this->input->post('procesador'),
				'soac' => $this->input->post('soac'),
				'sonu' => $this->input->post('sonu'),
				'software' => $this->input->post('software'),
				'hd' => $this->input->post('hd'),
				'desc' => $this->input->post('desc'),
            );
            
            $computadora_id = $this->Computadora_model->add_computadora($params);
            redirect('computadora/index');
        }
        else
        {            
            $data['_view'] = 'computadora/add';
            $this->load->view('_template_principal',$data);
        }
    }  

    /*
     * Editing a computadora
     */
    function edit($id)
    {   
        // check if the computadora exists before trying to edit it
        $data['computadora'] = $this->Computadora_model->get_computadora($id);
        
        if(isset($data['computadora']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'tipoc' => $this->input->post('tipoc'),
					'ram' => $this->input->post('ram'),
					'procesador' => $this->input->post('procesador'),
					'soac' => $this->input->post('soac'),
					'sonu' => $this->input->post('sonu'),
					'software' => $this->input->post('software'),
					'hd' => $this->input->post('hd'),
					'desc' => $this->input->post('desc'),
                );

                $this->Computadora_model->update_computadora($id,$params);            
                redirect('Equipos');
            }
            else
            {
                $data['_view'] = 'Equipos';
                $this->load->view('_template_principal',$data);
            }
        }
        else
            show_error('The computadora you are trying to edit does not exist.');
    } 

    /*
     * Deleting computadora
     */
    function remove($id)
    {
        $computadora = $this->Computadora_model->get_computadora($id);

        // check if the computadora exists before trying to delete it
        if(isset($computadora['id']))
        {
            $this->Computadora_model->delete_computadora($id);
            redirect('Equipos');
        }
        else
            show_error('The computadora you are trying to delete does not exist.');
    }

    /* Funcion para edita computadora*/
    public function datafcomputadora($id)
    {
        echo json_encode($this->Computadora_model->get_computadora($id));
    }
}
