<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Computadora_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get computadora by id
     */
    function get_computadora($id)
    {
        return $this->db->get_where('computadoras',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all computadoras
     */
    function get_all_computadoras()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('computadoras')->result_array();
    }
        
    /*
     * function to add new computadora
     */
    function add_computadora($params)
    {
        $this->db->insert('computadoras',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update computadora
     */
    function update_computadora($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('computadoras',$params);
    }
    
    /*
     * function to delete computadora
     */
    function delete_computadora($id)
    {
        return $this->db->delete('computadoras',array('id'=>$id));
    }
}
