<?php
/* 
 * systemsettings
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Systemsettings_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get systemsettings by id
     */
    function get_systemsettings($id)
    {
        return $this->db->get_where('systemsettings',array('id'=>$id))->row_array();
    }

    function get_data($rqs, $data, $rtn)
    {
        $info = $this->db->get_where('systemsettings',array($rqs=>$data))->row_array();
        return $info[$rtn];
    }
        
    /*
     * Get all systemsettings
     */
    function get_all_systemsettings()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('systemsettings')->result_array();
    }
        
    /*
     * function to add new systemsettings
     */
    function add_systemsettings($params)
    {
        $this->db->insert('systemsettings',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update systemsettings
     */
    function update_systemsettings($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('systemsettings',$params);
    }
    
    /*
     * function to delete systemsettings
     */
    function delete_systemsettings($id)
    {
        return $this->db->delete('systemsettings',array('id'=>$id));
    }
}
