<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Ubicaciones_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get ubicacion by id
     */
    function get_ubicacion($id)
    {
        return $this->db->get_where('ubicaciones',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all ubicaciones
     */
    function get_all_ubicaciones()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('ubicaciones')->result_array();
    }
        
    /*
     * function to add new ubicacion
     */
    function add_ubicacion($params)
    {
        $this->db->insert('ubicaciones',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update ubicacion
     */
    function update_ubicacion($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('ubicaciones',$params);
    }
    
    /*
     * function to delete ubicacion
     */
    function delete_ubicacion($id)
    {
        return $this->db->delete('ubicaciones',array('id'=>$id));
    }
}

?>