<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get user by id
     */
    function get_user($id)
    {
        return $this->db->get_where('users',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all users
     */
    function get_all_users()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('users')->result_array();

    }
    function myjoin()
    {
        //solo se ocupa para consultas especificas
        $this->db
                    ->select('puestos.nombre AS pnombre')
                    ->select('puestos.id AS pid')
                    ->select('entidades.nombre AS enombre')
                    ->select('entidades.id AS eid')
                    ->select('departamentos.nombre AS dnombre')
                    ->select('departamentos.id AS did')
                    ->select('ubicaciones.nombre AS unombre')
                    ->select('ubicaciones.id AS uid')
                    ->join ('puestos', 'users.puesto = puestos.id' , 'left')
                    ->join ('entidades', 'users.entidad = entidades.id' , 'left')
                    ->join('departamentos', 'users.departamento = departamentos.id' , 'left')
                    ->join('ubicaciones', 'users.ubicaciontrabajo = ubicaciones.id' , 'left');
        //$this->db->where('users.id',7);
    return $datosuser = $this->db->get('users')->result_array();
    }

       
    /*
     * function to add new user
     */
    function add_user($params)
    {
        $this->db->insert('users',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update user
     */
    function update_user($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('users',$params);
    }
    
    /*
     * function to delete user
     */
    function delete_user($id)
    {
        return $this->db->delete('users',array('id'=>$id));
    }
}
